#!/usr/bin/env python3
"""Embed the current source zip as a TypeScript module.

Reads shiftedtone-source.zip and writes src/convex/_sourceSnapshot.ts, which
exports the zip as base64 so the Convex HTTP router can serve it at
/source-zip (letting the Codespace download the snapshot without any preview
URL or GitHub token). Run make-source-zip.py first.
"""

from __future__ import annotations

import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ZIP = os.path.join(ROOT, "shiftedtone-source.zip")
OUT = os.path.join(ROOT, "src", "convex", "_sourceSnapshot.ts")


def main() -> None:
    with open(ZIP, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")

    with open(OUT, "w") as f:
        f.write(
            "/**\n"
            " * GENERATED by scripts/embed-source-zip.py — do not edit by hand.\n"
            " * Base64 of shiftedtone-source.zip, served at /source-zip so the\n"
            " * snapshot can be fetched without any preview URL or GitHub token.\n"
            " * Regenerate: python3 scripts/make-source-zip.py && python3 scripts/embed-source-zip.py\n"
            " */\n"
            f'export const SOURCE_ZIP_B64 = "{b64}";\n'
        )

    size = os.path.getsize(OUT)
    print(f"wrote src/convex/_sourceSnapshot.ts ({size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
